### ISSUE TITLE
"Network not matched" when signing on Fractal Mainnet

### ISSUE THREAD

**Issue by gssvv** [unisat-wallet/extension#273]
## Problem
When I try to sign my PSBT for fractal bitcoin network, I get "Network not matched" error.
It works fine on my localhost, but shows this error on my cloud-hosted app.

<img width="390" alt="Image" src="https://github.com/user-attachments/assets/1516768a-a136-406e-bd73-19f8822e4a00" />

I also noticed that it works fine if I sign this PSBT from the console on magiceden.io or unisat.io, but fails on other domains like github.com or google.com (and also my own domain):

https://github.com/user-attachments/assets/f3c66e7e-217c-461c-b232-3bb508e5f11e

## How to reproduce
Here's an example of PSBT
```
window.unisat.signPsbt("cHNidP8BAP2RBAIAAAABgFiUjm8wy3VsdG635zow/9GGICUn8YZr2zV5BEytjI8BAAAAAP////8aSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDag9haiEAAAAAIlEgbnZBDINpzcdrcC7U5pQlbWqaPBI7oAD2FWxxMBERqfkAAAAAAAEBK9/baiEAAAAAIlEgbnZBDINpzcdrcC7U5pQlbWqaPBI7oAD2FWxxMBERqfkBFyCLYDVez6u3IjAZ4xiCkGAB9WfEUMDqBIVFMwKicxUGkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==" )
```

**Comment by gssvv** [comment]
I figured out this rule not in the extension itself, but on the API side:

This will request give no warning:
```bash
curl -X POST https://wallet-api-fractal.unisat.io/v5/tx/decode2 -H 'Content-type: application/json' -d '{"psbtHex":"cHNidP8BAP2RBAIAAAABgFiUjm8wy3VsdG635zow/9GGICUn8YZr2zV5BEytjI8BAAAAAP////8aSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDakoEAAAAAAAAIlEgHhP8Py06srgcs/pXjFZ0+lUqMf0yIla3fHiQEWgIA2pKBAAAAAAAACJRIB4T/D8tOrK4HLP6V4xWdPpVKjH9MiJWt3x4kBFoCANqSgQAAAAAAAAiUSAeE/w/LTqyuByz+leMVnT6VSox/TIiVrd8eJARaAgDag9haiEAAAAAIlEgbnZBDINpzcdrcC7U5pQlbWqaPBI7oAD2FWxxMBERqfkAAAAAAAEBK9/baiEAAAAAIlEgbnZBDINpzcdrcC7U5pQlbWqaPBI7oAD2FWxxMBERqfkBFyCLYDVez6u3IjAZ4xiCkGAB9WfEUMDqBIVFMwKicxUGkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==", "website": "https://magiceden.io" }'
```

Response:
```json
...
"risks": [],
...
```

But change website to sth like `https://google.com` and it will return:
```json
...
   "risks": [
      {
        "type": 2,
        "level": "critical",
        "title": "'Network not matched' was detected.",
        "desc": "This transaction is not on current Network, proceeding may result in asset loss."
      }
    ],
...
```

I believe popular websites like magiceden or unisat are simply whitelisted here

**Comment by slient-coder** [comment]
When attempting to sign a transaction that spends a UTXO not present on the current blockchain, this error will be thrown.
However, in your example, the UTXO to be signed does exist on the Fractal network—it has simply already been spent. In this case, the error should not be thrown. We have already fixed this issue.

**Comment by gssvv** [comment]
> Are you still encountering this issue? Does your dapp’s logic require users to sign an input that has not yet been broadcast?

@slient-coder Yes, it's still an issue.

I'm using `signPsbt` method of unisat. Users are unable to sign their TX before broadcasting.

> Does your dapp’s logic require users to sign an input that has not yet been broadcast?

Generally yes, but in this specific case it doesn't allow me to sign even the broadcasted input.

My app was working fine a few days ago and I believe this issue was introduced with one of the recent updates on Unisat API.

**Comment by slient-coder** [comment]
It was indeed an issue caused by a recent update, but it has now been fixed. You can check again.
