### ISSUE TITLE
Cannot sign psbt that unlocks multi sign script

### ISSUE THREAD

**Issue by brinzi** [unisat-wallet/extension#86]
I've built a P2TR multisgn script that requires k-of-n signatures to be valid. However, I cannot build the unlock PSBT using unisat because of the following line of code.

```js
if (account.address === address) { --> here is the issue
    toSignInputs.push({
      index,
      publicKey: account.pubkey,
      sighashTypes: v.sighashType ? [v.sighashType] : undefined
    });
```

https://github.com/unisat-wallet/extension/blob/37491384ca5ad74eea68c00b2bf912994fd868e2/src/background/controller/wallet.ts#L385C43-L385C43

Is it possible to sign any arbitrary PSBT, even if the address of the script does not match the current selected account in Unisat?

**Comment by fess-v** [comment]
Facing the same issue, can anyone take a look at it? Multisignature PSBTs for P2TR don't work, inputs are not being signed with Unisat

**Comment by huanniangstudio** [comment]
Fixed in v1.1.30

**Comment by fess-v** [comment]
@GGG888GGG @huanniangstudio 
It doesn't work on our side :(
We use Taproot multisig scripts with leaf execution paths (not internal key).
Tested the same PSBT hashes with Hiro/Xverse just to be sure we're doing it right and it was successful (execution too), so the problem still exists in Unisat
![image](https://github.com/unisat-wallet/extension/assets/26626714/077f10d3-ff92-4a67-b077-e6fc4e0f4f92)
Thanks for your help in advance

**Comment by fess-v** [comment]
Attaching the code to sign PSBT on our side, `signerPublicKey` - is the connected Unisat wallet key

```javascript
  const signPsbtOptions = {
    autoFinalized: false,
    toSignInputs: [...(Array(psbt.inputCount).keys() as any)].map((i) => ({
      index: i,
      publicKey: signerPublicKey,
    })),
  };

  // @ts-ignore
  const result = await window.unisat.signPsbt(psbt.toHex(), signPsbtOptions);
  ```
  @huanniangstudio @GGG888GGG

**Comment by mustvlad** [comment]
> @GGG888GGG @huanniangstudio It doesn't work on our side :( We use Taproot multisig scripts with leaf execution paths (not internal key). Tested the same PSBT hashes with Hiro/Xverse just to be sure we're doing it right and it was successful (execution too), so the problem still exists in Unisat ![image](https://user-images.githubusercontent.com/26626714/264377526-077f10d3-ff92-4a67-b077-e6fc4e0f4f92.png) Thanks for your help in advance

We have the same issue. Works well with xVerse.

**Comment by GGG888GGG** [comment]
@mustvlad forwarded to our dev. Please kindly wait.

**Comment by huanniangstudio** [comment]
We have fixed this bug in v1.1.31

When signing and unlocking Taproot addresses, the tweakSigner is used by default for signature generation. Set "disableTweakSigner:true" to sign with the original private key.

Example:
```
unisat.signPsbt("xxxxxxxx",{toSignInputs:[{index:0,publicKey:"xxxxxx",disableTweakSigner:true}],autoFinalized:false})

```

**Comment by fess-v** [comment]
Works perfect, thanks @huanniangstudio
